### PR TITLE
Fix `delivery-tracking/shipment-info` profile `shippo` and `dhl` maps

### PR DESCRIPTION
**Pull request by janhalama**
## Description

`shippo` and `dhl` maps are not compatible with latest @superfaceai/one-sdk@1.0.0

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by freaz — COMMENTED** [review]
Changes looks good, but recordings are stored without hash so tests won't pass.

**Comment by janhalama** [comment]
> Changes looks good, but recordings are stored without hash so tests won't pass.

I updated recordings, snapshots and rebased with `chore/update-sf-dependencies` branch.

**Review by freaz — APPROVED** [review]
Good one

**Review by freaz — CHANGES_REQUESTED** [review]
Please check output of `yarn capabilities:lint --profileId delivery-tracking/shipment-info` there seems to be still 6 issues.

**Comment by freaz** [comment]
And looks it is just mock map, with problems.

**Comment by janhalama** [comment]
> yarn capabilities:lint --profileId delivery-tracking/shipment-info

Fixed linter errors in mock map. We should look into the linter, I do not think there was anything wrong with the code.

**Comment by freaz** [comment]
You are right. Seems to be all over the same story about type folding. @martinalbert @Jakub-Vacek am I right?

**Review by freaz — APPROVED** [review]
I hope :D

**Comment by Jakub-Vacek** [comment]
Yep, there are like 2 - 3 things in validator that need to be fixed (later this week probably)

**Pull request merged**
