### PR TITLE
feat: Include entity type in Id for use case `CreateCandidate`

### PR DESCRIPTION
**Pull request by martinalbert**
## Description
Adds entity type prefix to id of candidate.

## Motivation and Context
Discussion in [this comment](https://github.com/superfaceai/station/pull/306#discussion_r1049570684), main reason is support other use cases with different providers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by janhalama** [comment]
@martinalbert do we need it in case of Breezy HR provider? If I remember it well Breezy HR API has single id pool for candidates and leads.

**Comment by martinalbert** [comment]
Yes, workable should also have common pool, this was meant for other providers.

**Comment by janhalama** [comment]
> Yes, workable should also have common pool, this was meant for other providers.

I do not see the reason for adding the entity prefix in case of providers with single id pool for both candidates and leads. Structure of the ID is opaque for the client. We should be able to use directly the ID of the entity in case of Breezy HR and Workable providers.

**Comment by martinalbert** [comment]
Ok I misunderstood, it's different with breezy, but both have common id pool for lead and candidate. Breezy does not have stage `sourced`, you create a candidate with origin of `sourced`, but starts in first stage of a pipeline which is by default `applied`.

**Comment by martinalbert** [comment]
Closing this - not needed at the moment.

**Pull request closed without merging**
