### PR TITLE
fix(vcs): Smaller array size in pagination hack

### PR DESCRIPTION
**Pull request by Jakub-Vacek**
This PR fixes problem with allocation of large size Array during pagination.

Fixes: https://github.com/superfaceai/station/issues/266

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jnv — CHANGES_REQUESTED** [review]
Tests are failing. I am afraid this will require rerecording the tests, or at least recreate snapshots. Which is why I wanted you to take it over in the first place, assuming you have the tokens already set up. :wink:

**Comment by Jakub-Vacek** [comment]
Geocoding tests are failing 🤔 VCS tests pass correctly(there isn't any auth).

**Comment by Jakub-Vacek** [comment]
Okey, so some are just flaky :/

**Review by jnv — APPROVED** [review]
Technically I am self approving 😜

**Pull request merged**
